export const SET_PRODUCTS = '[PRODUCT] SET PRODUCTS';
export const SET_SHOPPING_CART = '[SHOPPING CART] GET SHOPPING CART';
export const ADD_TO_SHOPPING_CART = '[SHOPPING CART] ADD TO SHOPPING CART';
export const REMOVE_FROM_SHOPPING_CART = '[SHOPPING CART] REMOVE FROM SHOPPING CART';